export const homeObjOne = {
    id: 'about',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Premium bank',
    headline: 'Unlimited transactions with zero feed',
    description: "Get access to our exclusive app that allows you to send unlimited transactions without getting charged any feed",
    buttonLabel: 'Get started',
    imgStart: false,
    img: require('../../images/svg-1.svg').default,
    alt: "Car",
    dark: true,
    primary: true,
    darkText: false,
}

export const homeObjTwo = {
    id: 'discover',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'Unlimited Access',
    headline: 'Login to your account at any time',
    description: "We have you covered no matter where you are located, all you need is an internet connection and a phone or computer",
    buttonLabel: 'Learn more',
    imgStart: true,
    img: require('../../images/svg-2.svg').default,
    alt: "Pig",
    dark: false,
    primary: false,
    darkText: true,
}

export const homeObjThree = {
    id: 'signup',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'Join our team',
    headline: 'Creating an account is extremely easy',
    description: "Get everything set up and ready in under 10 minuted. All you need to do is add your information and you're ready to go!",
    buttonLabel: 'Start now',
    imgStart: false,
    img: require('../../images/svg-6.svg').default,
    alt: "Credit card",
    dark: false,
    primary: false,
    darkText: true,
}